
language: python

#env:
#  - PYTHON=python PYSUF='' PYVER=2.7 PIPVER=''
#  - PYTHON=python3 PYSUF='3' PYVER=3.2 PIPVER='==7.1.2'

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - pip install cython rtl
  - sudo pip install -e .

script: nosetests
