
language: python

#env:
#  - PYTHON=python PYSUF='' PYVER=2.7 PIPVER=''
#  - PYTHON=python3 PYSUF='3' PYVER=3.2 PIPVER='==7.1.2'

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "pypy"

before_install:
  - sudo apt-get update
  - sudo apt-get install gdb python$( python -c 'import sys; print("%d.%d" % sys.version_info[:2])' )-dbg || true
  - sudo pip install cython
  - sudo pip install rtl
  - dpkg -l gdb || true

install:
  - sudo pip install -e .

script: nosetests
